### ISSUE TITLE
Criar classe principal

### ISSUE THREAD

**Issue by RaulHax** [RaulHax/fluffy-octo-rutabaga#3]
A gente optou por fazer um sistema de Máquinas de Vendas.
Agora temos que decidir quais métodos uma máquina dessas precisa (ex.: DarTroco, IdentificarProduto, etc.)

**Comment by GuilhermeReal** [comment]
http://www.cranems.com/
O site da máquina.

**Comment by RaulHax** [comment]
site pra base do código: http://www.cplusplus.com/forum/beginner/121057/
